name_conversion = {"Bench Press (Barbell)": "Barbell Flat Bench Press",
                  "Overhead Press (Barbell)": "Barbell Shoulder Press (standing)",
                  "Crunch (Machine)": "Machine Crunch (seated)",
                  "Reverse Curl (Barbell)": "Reverse Barbell Forearm Curl (standing)",
                  "Bicep Curl (Barbell)": "Barbell Biceps Curl (standing)",
                  "Incline Row (Dumbbell)": "Dumbbell Flat High Bench Row (prone)",
                  "Upright Row (Barbell)": "Barbell Upright Row (standing)",
                  "Chin Up": "Pull-ups| Underhand Medium Grip",
                  "Lateral Raise (Dumbbell)": "Dumbbell Lateral Raise (standing)",
                  "Triceps Extension": "Pulley Machine Rope Triceps Press (standing)",
                  "Chest Press (Machine)": "Machine Front Press (seated)",
                   "Chest Fly": "Machine Fly (seated)",
                   "Overhead Press (Smith Machine)": "Smith Machine Shoulder Press (seated)",
                   "Chest Dip (Assisted)": "Supported Machine Dips",
                   "Hanging Leg Raise": "Leg Raise (hanging)",
                   "Leg Extension (Machine)": "Machine Leg Extension (seated)",
                   "Standing Calf Raise (Dumbbell)": "Barbell Calf Raise (standing)",
                   "Deadlift (Barbell)": "Barbell Deadlift",
                   "Squat (Barbell)": "Barbell Squats (standing)",
                   "Bicep Curl (Machine)": "Scott Machine Biceps Curl (seated)",
                   "Seated Row (Machine)": "Leverage Machine Row (seated)",
                   "Bent Over Row (Barbell)": "Barbell Row| Bent Over (standing)",
                   "Calf Press on Seated Leg Press": "Machine Calf Raise (seated)",
                   "Bent Over Row (Dumbbell)": "Dumbbell Row| Bent OVer (standing)",
                   "Hanging Knee Raise": "Knee Raise (hanging)",
                   "Standing Calf Raise (Machine)": "Machine Calf Raise (standing)",
                   "Lat Pulldown (Machine)": "Pulley Machine Pulldown To Chest| Wide Grip (seated)",
                   "Lying Leg Curl (Machine)": "Machine Leg Curl (prone)",
                   "Bench Dip": "Dips| Raised Legs",
                   "Pull Up": "Pull-ups| Overhand Medium Grip",
                   "Chest Dip": "Bar Dips",
                   "Bicep Curl (Dumbbell)": "Dumbbell Biceps Curl (standing)",
                   "Seated Leg Curl (Machine)": "Machine Leg Curl (seated)",
                   "Decline Crunch": "Crunches (decline)",
                   "Reverse Fly (Machine)": "Reverse Machine Flys (seated)",
                   "Cable Kickback": "Pulley Machine Triceps Kickback (bent over)",
                   "Skullcrusher (Barbell)": "EZ-Bar Triceps French Press (lying)",
                   "Shoulder Press (Machine)": "Machine Shoulder Press (seated)",
                   "Incline Curl (Dumbbell)": "Dumbbell Biceps Curl (incline)",
                   "Hammer Curl (Dumbbell)": "Dumbbell Biceps Hammer Curl (standing)",
                   "Seated Row (Cable)": "Pulley Machine Row (seated)",
                   "Pull Up (Assisted)": "Supported Machine Pull-ups| Overhand Medium Grip",
                   "Plank": "Planks",
                   "Leg Press": "Machine Leg Press (incline)",
                   "Triceps Extension (Cable)": "Pulley Machine Rope Triceps Press (standing)",
                   "Cable Crossover": "Pulley Machine Crossover (standing)",
                   "Bench Press - Close Grip (Barbell)": "Barbell Flat Bench Press| Close Grip",
                   "Lat Pulldown (Cable)": "Pulley Machine Pulldown To Chest| Wide Grip (seated)",
                   "Knee Raise (Captain's Chair)": "Knee Raise| Rest On Arms",
                   "Hack Squat": "Machine Squats (incline)",
                   "Seated Calf Raise (Machine)": "Machine Calf Raise (seated)",
                   "Back Extension": "Hyperextension Bench Side Crunch",
                   "Triceps Pushdown (Cable - Straight Bar)": "Pulley Machine Triceps Press (standing)",
                   "Incline Bench Press (Barbell)": "Barbell Bench Press (incline)",
                   "Shrug (Dumbbell)": "Dumbbell Shrugs (standing)",
                   "Chin Up (Assisted)": "Supported Machine Pull-ups| Underhand Medium Grip"
                   }
