# left is Hevy/Strong, right is Gymrun
name_conversion = {"Bench Press (Barbell)": "Barbell Flat Bench Press",
                   "Overhead Press (Barbell)": "Barbell Shoulder Press (standing)",
                   "Crunch (Machine)": "Machine Crunch (seated)",
                   "Reverse Curl (Barbell)": "Reverse Barbell Forearm Curl (standing)",
                   "Bicep Curl (Barbell)": "Barbell Biceps Curl (standing)",
                   "Incline Row (Dumbbell)": "Dumbbell Flat High Bench Row (prone)",
                   "Upright Row (Barbell)": "Barbell Upright Row (standing)",
                   "Chin Up": "Pull-ups, Underhand Medium Grip",
                   "Lateral Raise (Dumbbell)": "Dumbbell Lateral Raise (standing)",
                   "Triceps Extension": "Pulley Machine Rope Triceps Press (standing)",
                   "Chest Press (Machine)": "Machine Front Press (seated)",
                   "Chest Fly": "Machine Fly (seated)",
                   "Overhead Press (Smith Machine)": "Smith Machine Shoulder Press (seated)",
                   "Chest Dip (Assisted)": "Supported Machine Dips",
                   "Hanging Leg Raise": "Leg Raise (hanging)",
                   "Leg Extension (Machine)": "Machine Leg Extension (seated)",
                   "Standing Calf Raise (Dumbbell)": "Barbell Calf Raise (standing)",
                   "Deadlift (Barbell)": "Barbell Deadlift",
                   "Squat (Barbell)": "Barbell Squats (standing)",
                   "Bicep Curl (Machine)": "Scott Machine Biceps Curl (seated)",
                   "Seated Row (Machine)": "Leverage Machine Row (seated)",
                   "Bent Over Row (Barbell)": "Barbell Row, Bent Over (standing)",
                   "Calf Press on Seated Leg Press": "Machine Calf Raise (seated)",
                   "Bent Over Row (Dumbbell)": "Dumbbell Row, Bent OVer (standing)",
                   "Hanging Knee Raise": "Knee Raise (hanging)",
                   "Standing Calf Raise (Machine)": "Machine Calf Raise (standing)",
                   "Lat Pulldown (Machine)": "Pulley Machine Pulldown To Chest, Wide Grip (seated)",
                   "Lying Leg Curl (Machine)": "Machine Leg Curl (prone)",
                   "Bench Dip": "Dips, Raised Legs",
                   "Pull Up": "Pull-ups, Overhand Medium Grip",
                   "Chest Dip": "Bar Dips",
                   "Bicep Curl (Dumbbell)": "Dumbbell Biceps Curl (standing)",
                   "Seated Leg Curl (Machine)": "Machine Leg Curl (seated)",
                   "Decline Crunch": "Crunches (decline)",
                   "Reverse Fly (Machine)": "Reverse Machine Flys (seated)",
                   "Cable Kickback": "Pulley Machine Triceps Kickback (bent over)",
                   "Skullcrusher (Barbell)": "EZ-Bar Triceps French Press (lying)",
                   "Shoulder Press (Machine)": "Machine Shoulder Press (seated)",
                   "Incline Curl (Dumbbell)": "Dumbbell Biceps Curl (incline)",
                   "Hammer Curl (Dumbbell)": "Dumbbell Biceps Hammer Curl (standing)",
                   "Seated Row (Cable)": "Pulley Machine Row (seated)",
                   "Pull Up (Assisted)": "Supported Machine Pull-ups, Overhand Medium Grip",
                   "Plank": "Planks",
                   "Leg Press": "Machine Leg Press (incline)",
                   "Triceps Extension (Cable)": "Pulley Machine Rope Triceps Press (standing)",
                   "Cable Crossover": "Pulley Machine Crossover (standing)",
                   "Bench Press - Close Grip (Barbell)": "Barbell Flat Bench Press, Close Grip",
                   "Lat Pulldown (Cable)": "Pulley Machine Pulldown To Chest, Wide Grip (seated)",
                   "Knee Raise (Captain's Chair)": "Knee Raise, Rest On Arms",
                   "Hack Squat": "Machine Squats (incline)",
                   "Seated Calf Raise (Machine)": "Machine Calf Raise (seated)",
                   "Back Extension": "Hyperextension Bench Side Crunch",
                   "Triceps Pushdown (Cable - Straight Bar)": "Pulley Machine Triceps Press (standing)",
                   "Incline Bench Press (Barbell)": "Barbell Bench Press (incline)",
                   "Shrug (Dumbbell)": "Dumbbell Shrugs (standing)",
                   "Chin Up (Assisted)": "Supported Machine Pull-ups, Underhand Medium Grip",
                   "Face Pull": "Face Pull",
                   "Dumbbell Row": "Dumbbell Row, Bent Over (standing)",
                   "Reverse Grip Lat Pulldown": "Pulley Machine Pulldown To Chest, Underhand Close Grip (seated)",
                   "Triceps Pushdown": "Pulley Machine Triceps Press V-Bar (standing)",
                   "Single Leg Press (Machine)": "Single Leg Leg Press",
                   "Dead Hang": "Dead Hang",
                   "Front Squat": "Barbell Front Squats (standing)",
                   "Triceps Extension (Machine)": "Machine Triceps Press (seated)",
                   "Bicep Curl (Cable)": "Pulley Machine Single Arm Biceps Curl",
                   "Lateral Raise (Cable)": "Pulley Machine Lateral Raise (standing)",
                   "Lateral Raise (Machine)": "Machine Lateral Raise (seated)",
                   "Shrug (Barbell)": "Barbell Shrugs (standing)",
                   "Bench Press (Dumbbell)": "Dumbbell Flat Bench Press",
                   "Lat Pulldown (Machine)": "Leverage Machine Pulldown (seated)",
                   "Back Extension (Weighted Hyperextension)": "Machine Hyperextensions",
                   "Russian Twist (Bodyweight)": "Twisting Air Bike Crunches",
                   "Single Arm Lat Pulldown": "One Arm Lat Pull-In ",
                   "Scapular Pull Ups": "Scapular Pull-up",
                   "Rope Straight Arm Pulldown": "Pulley Machine Pullover (standing)",
                   "Shrug (Dumbbell)": "Dumbbell Shrug (incline)",
                   "Upright Row (Cable)": "Pulley Machine Upright Row (standing)",
                   "Incline Bench Press (Dumbbell)": "Dumbbell Bench Press (incline)",
                   "Shrug (Dumbbell)": "Dumbbell Shrugs (standing)",
                   "Torso Rotation": "Torso Rotation",
                   "Shoulder Press (Dumbbell)": "Dumbbell Shoulder Press (seated)",
                   "Inverted Row": "Australian Pull Up",
                   "Dumbbell Row": "One Arm Dumbbell Row",
                   "Romanian Deadlift (Barbell)": "Romanian Deadlift",
                   "Triceps Extension (Cable)": "Single Arm Triceps Extensions (ropes)",
                   "Triceps Extension (Cable)": "Overhead Pulley Machine Rope Triceps Press (bent over)",
                   "Dumbbell Row": "Dumbbell Row, Bent Over (standing)",
                   "Shrug (Dumbbell)": "Dumbbell Shrug (incline)",
                   }

# left is Gymrun, right is Hevy/Strong
conversion_name = {'Barbell Flat Bench Press': 'Bench Press (Barbell)',
                   'Barbell Shoulder Press (standing)': 'Overhead Press (Barbell)',
                   'Machine Crunch (seated)': 'Crunch (Machine)',
                   'Reverse Barbell Forearm Curl (standing)': 'Reverse Curl (Barbell)',
                   'Barbell Biceps Curl (standing)': 'Bicep Curl (Barbell)',
                   'Dumbbell Flat High Bench Row (prone)': 'Incline Row (Dumbbell)',
                   'Barbell Upright Row (standing)': 'Upright Row (Barbell)',
                   'Pull-ups, Underhand Medium Grip': 'Chin Up',
                   'Dumbbell Lateral Raise (standing)': 'Lateral Raise (Dumbbell)',
                   'Pulley Machine Rope Triceps Press (standing)': 'Triceps Extension',
                   'Machine Front Press (seated)': 'Chest Press (Machine)',
                   'Machine Fly (seated)': 'Chest Fly',
                   'Smith Machine Shoulder Press (seated)': 'Overhead Press (Smith Machine)',
                   'Supported Machine Dips': 'Chest Dip (Assisted)',
                   'Leg Raise (hanging)': 'Hanging Leg Raise',
                   'Machine Leg Extension (seated)': 'Leg Extension (Machine)',
                   'Barbell Calf Raise (standing)': 'Standing Calf Raise (Dumbbell)',
                   'Barbell Deadlift': 'Deadlift (Barbell)',
                   'Barbell Squats (standing)': 'Squat (Barbell)',
                   'Scott Machine Biceps Curl (seated)': 'Bicep Curl (Machine)',
                   'Leverage Machine Row (seated)': 'Seated Row (Machine)',
                   'Barbell Row, Bent Over (standing)': 'Bent Over Row (Barbell)',
                   'Machine Calf Raise (seated)': 'Seated Calf Raise (Machine)',
                   'Dumbbell Row, Bent OVer (standing)': 'Bent Over Row (Dumbbell)',
                   'Knee Raise (hanging)': 'Hanging Knee Raise',
                   'Machine Calf Raise (standing)': 'Standing Calf Raise (Machine)',
                   'Leverage Machine Pulldown (seated)': 'Lat Pulldown (Machine)',
                   'Machine Leg Curl (prone)': 'Lying Leg Curl (Machine)',
                   'Dips, Raised Legs': 'Bench Dip',
                   'Pull-ups, Overhand Medium Grip': 'Pull Up',
                   'Bar Dips': 'Chest Dip',
                   'Dumbbell Biceps Curl (standing)': 'Bicep Curl (Dumbbell)',
                   'Machine Leg Curl (seated)': 'Seated Leg Curl (Machine)',
                   'Crunches (decline)': 'Decline Crunch',
                   'Reverse Machine Flys (seated)': 'Reverse Fly (Machine)',
                   'Pulley Machine Triceps Kickback (bent over)': 'Cable Kickback',
                   'EZ-Bar Triceps French Press (lying)': 'Skullcrusher (Barbell)',
                   'Machine Shoulder Press (seated)': 'Shoulder Press (Machine)',
                   'Dumbbell Biceps Curl (incline)': 'Incline Curl (Dumbbell)',
                   'Dumbbell Biceps Hammer Curl (standing)': 'Hammer Curl (Dumbbell)',
                   'Pulley Machine Row (seated)': 'Seated Row (Cable)',
                   'Supported Machine Pull-ups, Overhand Medium Grip': 'Pull Up (Assisted)', 'Planks': 'Plank',
                   'Machine Leg Press (incline)': 'Leg Press',
                   'Overhead Pulley Machine Rope Triceps Press (bent over)': 'Triceps Extension (Cable)',
                   'Pulley Machine Crossover (standing)': 'Cable Crossover',
                   'Barbell Flat Bench Press, Close Grip': 'Bench Press - Close Grip (Barbell)',
                   'Pulley Machine Pulldown To Chest, Wide Grip (seated)': 'Lat Pulldown (Cable)',
                   'Knee Raise, Rest On Arms': "Knee Raise (Captain's Chair)", 'Machine Squats (incline)': 'Hack Squat',
                   'Hyperextension Bench Side Crunch': 'Back Extension',
                   'Pulley Machine Triceps Press (standing)': 'Triceps Pushdown (Cable - Straight Bar)',
                   'Barbell Bench Press (incline)': 'Incline Bench Press (Barbell)',
                   'Dumbbell Shrug (incline)': 'Shrug (Dumbbell)',
                   'Supported Machine Pull-ups, Underhand Medium Grip': 'Chin Up (Assisted)', 'Face Pull': 'Face Pull',
                   'Dumbbell Row, Bent Over (standing)': 'Dumbbell Row',
                   'Pulley Machine Pulldown To Chest, Underhand Close Grip (seated)': 'Reverse Grip Lat Pulldown',
                   'Pulley Machine Triceps Press V-Bar (standing)': 'Triceps Pushdown',
                   'Single Leg Leg Press': 'Single Leg Press (Machine)', 'Dead Hang': 'Dead Hang',
                   'Barbell Front Squats (standing)': 'Front Squat',
                   'Machine Triceps Press (seated)': 'Triceps Extension (Machine)',
                   'Pulley Machine Single Arm Biceps Curl': 'Bicep Curl (Cable)',
                   'Pulley Machine Lateral Raise (standing)': 'Lateral Raise (Cable)',
                   'Machine Lateral Raise (seated)': 'Lateral Raise (Machine)',
                   'Barbell Shrugs (standing)': 'Shrug (Barbell)',
                   'Dumbbell Flat Bench Press': 'Bench Press (Dumbbell)',
                   'Machine Hyperextensions': 'Back Extension (Weighted Hyperextension)',
                   'Twisting Air Bike Crunches': 'Russian Twist (Bodyweight)',
                   'One Arm Lat Pull-In ': 'Single Arm Lat Pulldown',
                   'Scapular Pull-up': 'Scapular Pull Ups',
                   'Pulley Machine Pullover (standing)': 'Rope Straight Arm Pulldown',
                   'Pulley Machine Upright Row (standing)': 'Upright Row (Cable)',
                   'Dumbbell Bench Press (incline)': 'Incline Bench Press (Dumbbell)',
                   'Torso Rotation': 'Torso Rotation',
                   'Dumbbell Shoulder Press (seated)': 'Shoulder Press (Dumbbell)',
                   'Australian Pull Up': 'Inverted Row',
                   'Romanian Deadlift': 'Romanian Deadlift (Barbell)',
                   'One Arm Dumbbell Row': 'Dumbbell Row',
                   'Dumbbell Shrugs (standing)': 'Shrug (Dumbbell)',
                   'Single Arm Triceps Extensions (ropes)': 'Triceps Extension (Cable)'
                   }

bodyweight_exercises = ["Knee Raise (Captain's Chair)",
                        "Plank",
                        "Hanging Knee Raise",
                        "Hanging Leg Raise",
                        "Pull Up",
                        "Chest Dip (Assisted)",
                        "Back Extension",
                        "Inverted Row (Bodyweight)",
                        "Decline Crunch",
                        "Chest Dip",
                        "Chin Up",
                        "Russian Twist (Bodyweight)",
                        "Scapular Pull Ups",
                        "Inverted Row",
                        "Dead Hang",
                        ]
